# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: codeigniter3-scaffold 1.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "codeigniter3-scaffold"
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["jlamim", "universidadecodeigniter"]
  s.date = "2016-09-10"
  s.description = "Simple scaffold generator for codeigniter 3.1.0 now using Twitter Bootstrap templates!"
  s.email = "contato@universidadecodeigniter.com.br"
  s.executables = ["codeigniter3-scaffold"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README",
    "README.md"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/codeigniter3-scaffold",
    "codeigniter3-scaffold.gemspec",
    "lib/codeigniter_scaffold.rb",
    "lib/codeigniter_scaffold/attribute.rb",
    "lib/codeigniter_scaffold/command/help.rb",
    "lib/codeigniter_scaffold/command/init.rb",
    "lib/codeigniter_scaffold/command/scaffold.rb",
    "lib/codeigniter_scaffold/executor.rb",
    "lib/resources/ci_3.1.0.zip",
    "lib/resources/controller.php",
    "lib/resources/migration.sql",
    "lib/resources/model.php",
    "lib/resources/view_create.php",
    "lib/resources/view_index.php",
    "spec/codeigniter_scaffold/command/help_spec.rb",
    "spec/codeigniter_scaffold/command/init_spec.rb",
    "spec/codeigniter_scaffold/command/scaffold_spec.rb",
    "spec/codeigniter_scaffold/executor_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/universidadecodeigniter/codeigniter-scaffold"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "Simple gem for generate scaffolds for codeigniter 3"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubyzip>, [">= 0"])
      s.add_development_dependency(%q<linecache19>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug-base19x>, ["~> 0.11.30.pre4"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.4"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rubyzip>, [">= 0"])
      s.add_dependency(%q<linecache19>, [">= 0"])
      s.add_dependency(%q<ruby-debug-base19x>, ["~> 0.11.30.pre4"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.1.4"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rubyzip>, [">= 0"])
    s.add_dependency(%q<linecache19>, [">= 0"])
    s.add_dependency(%q<ruby-debug-base19x>, ["~> 0.11.30.pre4"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.1.4"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

